In [1]:
import numpy as np

# 创建数组

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [5]:
a = np.array((1,2,3))

In [6]:
a

array([1, 2, 3])

In [8]:
a = np.array([[1,2,3], [1,2,3]])

In [9]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [10]:
a.ndim

2

In [11]:
a.shape

(2, 3)

In [13]:
a.dtype

dtype('int32')

In [15]:
a = np.zeros(10)

In [16]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
a.dtype

dtype('float64')

In [18]:
a = np.ones((2,5))

In [19]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
a.ndim

2

In [21]:
a.shape

(2, 5)

In [22]:
a.dtype

dtype('float64')

In [23]:
a = np.empty((2,3,4))  # 填入元组

In [24]:
a

array([[[1.14008073e-311, 1.14008073e-311, 1.13991440e-311,
         1.14008073e-311],
        [1.14008073e-311, 1.13991440e-311, 1.14008073e-311,
         1.14008073e-311],
        [1.13991440e-311, 1.14008073e-311, 1.14008073e-311,
         1.13991440e-311]],

       [[1.14008073e-311, 1.14008073e-311, 1.13991440e-311,
         1.14008073e-311],
        [1.14008073e-311, 1.13991440e-311, 1.14008073e-311,
         1.14008073e-311],
        [1.13991440e-311, 1.14008073e-311, 1.14008073e-311,
         1.13991440e-311]]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
x = np.linspace(0,10,100)  # 从0-10产生100个

In [29]:
y = np.sin(x)

In [31]:
a = np.array([1,2,3], dtype=np.float32)

In [32]:
a.dtype

dtype('float32')

In [33]:
np.zeros(10, dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 数据类型

In [34]:
a = np.array([True, False, False, True])

In [35]:
a.dtype

dtype('bool')

In [36]:
np.array(['sd', 'sde'])

array(['sd', 'sde'], dtype='<U3')

# 转换类型

In [37]:
a.astype(np.int16)  

array([1, 0, 0, 1], dtype=int16)

In [44]:
a = np.array([1.1, 2.2, 3.7])

In [45]:
a.astype(np.float16)

array([1.1, 2.2, 3.7], dtype=float16)

In [46]:
a.astype(np.int32)  # 直接去掉小数点，不会进位

array([1, 2, 3])