In [1]:
import numpy as np

# 数组切片

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5:8]

array([5, 6, 7])

In [7]:
arr[2:8:2]  # 步长为2

array([2, 4, 6])

In [8]:
a2 = arr[5:8]  # 只是原来数据的视图

In [9]:
a2

array([5, 6, 7])

In [10]:
a2[0] = 100

In [11]:
a2

array([100,   6,   7])

In [12]:
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [13]:
a3 = arr[5:8].copy()  # 处理a3不会改变原来的array，深拷贝

In [14]:
a3[1] = 1000

In [15]:
a3

array([ 100, 1000,    7])

In [16]:
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [17]:
a4 = np.arange(24).reshape(2,3,4)

In [18]:
a4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
a4[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
a4[1][1][2]   # 数据索引

18

In [21]:
a4[0][2][1]

9

In [23]:
a4[0][2][1]=100

In [24]:
a4[0,2,1]

100

In [25]:
a4[:,0,:3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [26]:
a4[:,0,2]

array([ 2, 14])

In [28]:
a4[:,:,2:]

array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])

# 数组索引

In [29]:
a = np.arange(20)

In [30]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
a >10  # 返回布尔值

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [35]:
a[a>10]  # 返回大于10的值

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
(a>5)&(a<14)&(a%2==0)

array([False, False, False, False, False, False,  True, False,  True,
       False,  True, False,  True, False, False, False, False, False,
       False, False])

In [38]:
a[(a>5)&(a<14)&(a%2==0)]

array([ 6,  8, 10, 12])

In [39]:
a[(a<3)|(a>16)]

array([ 0,  1,  2, 17, 18, 19])

In [40]:
a = np.arange(24).reshape(2,3,4)

In [41]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [42]:
a[(a>10)&(a%2 != 0)]  #  返回一维数组

array([11, 13, 15, 17, 19, 21, 23])

In [43]:
a[~(a<=10)]  # ~取反

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])