In [1]:
import numpy as np

# numpy广播

In [2]:
a = np.arange(10).reshape(2,5)

In [3]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
a+10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
a*100

array([[  0, 100, 200, 300, 400],
       [500, 600, 700, 800, 900]])

In [6]:
a + a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [7]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
a1 = np.arange(5)

In [12]:
a1

array([0, 1, 2, 3, 4])

In [9]:
a1.shape

(5,)

In [10]:
a.shape

(2, 5)

In [11]:
a + a1

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [15]:
a1 = np.arange(2)

In [17]:
a1 = a1.reshape(2,1)
a1

array([[0],
       [1]])

In [18]:
a + a1

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

# 转置

In [19]:
a.shape

(2, 5)

In [20]:
a.T 

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])