In [1]:
import numpy as np

In [2]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [3]:
a

array([[1, 2],
       [3, 4]])

In [4]:
b

array([[5, 6],
       [7, 8]])

In [5]:
np.concatenate((a, b))  # 默认沿着0轴合并，
#上下方向为0轴（对行的数量变化），左右方向为1轴（对列的数量变化）

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [7]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

In [8]:
np.concatenate((a1,a2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.concatenate((a1,a2), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [9]:
np.stack((a1,a2))  # 变成一个二维数组，增加维度

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
a1

array([1, 2, 3, 4])

In [12]:
np.append(a1, 5)

array([1, 2, 3, 4, 5])

In [13]:
b

array([[5, 6],
       [7, 8]])

In [15]:
np.append(b, [9,10])  # 没有添加轴，默认展开

array([ 5,  6,  7,  8,  9, 10])

In [16]:
np.append(b, [[9,10]], axis=0)

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
np.append(b, [[9],[10]], axis=1)

array([[ 5,  6,  9],
       [ 7,  8, 10]])

# 去重元素

In [18]:
a = np.array([1,2,1,1,2,3,4,5,3,6,7,1,3,4])

In [19]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7])