In [1]:
import numpy as np

# 通用函数

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [6]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [7]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
a**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [9]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b = np.arange(10, 0, -1)

In [11]:
b

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [12]:
np.maximum(a,b) # 对比两个数组，取出较大值

array([10,  9,  8,  7,  6,  5,  6,  7,  8,  9])

In [13]:
a-b

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [15]:
np.subtract(a,b)

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [18]:
a[a >= b]  # a中大于b的元素

array([5, 6, 7, 8, 9])

# 统计方法

In [19]:
a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.mean(a)

4.5

In [21]:
a.mean()

4.5

In [22]:
np.sum(a)

45

In [23]:
a.sum()

45

In [28]:
a1 = a.reshape(2,5)
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
a1.mean(axis=1)  # 沿着行操作，得到一个列，列变化，axis=1

array([2., 7.])

In [30]:
a1.mean(axis=0)  # 沿着列操作，得到一个行，行变化，axis=0 

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [31]:
a1.sum(0)

array([ 5,  7,  9, 11, 13])

In [32]:
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
np.min(a1, axis=1)

array([0, 5])

In [35]:
np.max(a1, axis=0)

array([5, 6, 7, 8, 9])

In [36]:
np.std(a1, axis=0)  # 求方差

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [37]:
np.median(a1, axis=1)  # 中位值

array([1.41421356, 1.41421356])