In [ ]:
import numpy as np

# 排序与搜索

In [2]:
a = np.random.randn(10)

In [3]:
a.sort()

In [4]:
a

array([-1.24374988, -1.14107054, -0.91032698, -0.28023575, -0.23672439,
        0.08046446,  0.11477175,  0.17050015,  0.46202535,  1.20176413])

In [5]:
np.sort(a)

array([-1.24374988, -1.14107054, -0.91032698, -0.28023575, -0.23672439,
        0.08046446,  0.11477175,  0.17050015,  0.46202535,  1.20176413])

In [6]:
a.shape = 2,5 # 与reshape等价

In [7]:
a

array([[-1.24374988, -1.14107054, -0.91032698, -0.28023575, -0.23672439],
       [ 0.08046446,  0.11477175,  0.17050015,  0.46202535,  1.20176413]])

In [8]:
a.sort(axis=1)

In [9]:
a

array([[-1.24374988, -1.14107054, -0.91032698, -0.28023575, -0.23672439],
       [ 0.08046446,  0.11477175,  0.17050015,  0.46202535,  1.20176413]])

In [10]:
a = np.array([2,4,1,3])

In [11]:
np.argsort(a)  # 返回排序后的索引值

array([2, 0, 3, 1], dtype=int64)

In [12]:
a[np.argsort(a)]

array([1, 2, 3, 4])

In [13]:
np.argmax(a)

1

In [14]:
np.argmin(a)

2

In [15]:
np.where(a>2)  # 返回大于2的索引

(array([1, 3], dtype=int64),)

In [16]:
a

array([2, 4, 1, 3])

In [17]:
b = np.array([9,5,6,7])

In [18]:
cond = np.array([True, False, False, False])

In [19]:
np.where(cond, a, b)  # cond为T时，在a中取值，cond为F时，在b中取值

array([2, 5, 6, 7])

In [20]:
a

array([2, 4, 1, 3])

In [21]:
a>2

array([False,  True, False,  True])

In [22]:
(a>2).sum()  # 大于2的个数

2

# 随机生成

In [24]:
np.random.randn(10)  # 生成标准正态分布随机数

array([-0.3852078 ,  0.26398796,  1.10516805,  0.56145967, -1.07792387,
        0.87151013, -0.32173178, -0.23252242,  2.33464405,  1.78008916])

In [25]:
np.random.randn(3,4)

array([[-0.64011158,  1.31757436,  0.03239044, -0.43987474],
       [ 0.16052866, -0.71199182, -0.18933139, -0.81974683],
       [-0.56920045,  0.08148741,  0.19549415, -0.92246344]])

In [28]:
np.random.normal(size=(3,4))  # 生成正态分布随机数

array([[-1.02330635,  0.48813601,  1.49042502, -1.06514994],
       [-1.49924928, -1.7177433 , -1.53255635,  0.48636287],
       [-1.20834167,  0.04854734, -0.12386447,  0.18136239]])

In [29]:
np.random.randint(1,10,(3,4))  # 生成自然数 范围1-9 3行4列

array([[8, 8, 7, 2],
       [7, 2, 3, 9],
       [2, 5, 5, 4]])

In [30]:
a

array([2, 4, 1, 3])

In [33]:
b = np.random.permutation(len(a))  # 乱序函数

In [32]:
a[np.random.permutation(len(a))]  # 每次运行得到一列乱序的值

array([2, 3, 4, 1])

In [34]:
a[b]

array([1, 3, 2, 4])

In [35]:
np.random.choice([1,2,3,4,5,6])  # 随机选一个数

6

In [37]:
np.random.choice([1,2,3,4,5,6], size=2)  # 随机选两个数

array([4, 5])

In [38]:
np.random.seed(5)  
# 指定随机种子，只对下一次random生效，随机种子不变，生成的随机数不变（伪随机数）

In [39]:
np.random.randn(3,4)

array([[ 0.44122749, -0.33087015,  2.43077119, -0.25209213],
       [ 0.10960984,  1.58248112, -0.9092324 , -0.59163666],
       [ 0.18760323, -0.32986996, -1.19276461, -0.20487651]])

In [40]:
np.random.seed(5)

In [41]:
np.random.randn(3,4)

array([[ 0.44122749, -0.33087015,  2.43077119, -0.25209213],
       [ 0.10960984,  1.58248112, -0.9092324 , -0.59163666],
       [ 0.18760323, -0.32986996, -1.19276461, -0.20487651]])

# 文件读写

In [42]:
a

array([2, 4, 1, 3])

In [44]:
np.save('./dataset/savea',a)

In [45]:
np.load('./dataset/savea.npy')

array([2, 4, 1, 3])

In [49]:
np.savetxt('./dataset/savea', a)

In [50]:
np.loadtxt('./dataset/savea')  # 默认float

array([2., 4., 1., 3.])