In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [2]:
data = pd.DataFrame({'one':[4, np.nan, 2, np.nan],
                     'two':[np.nan, 4, np.nan, 5],
                     'three':[5, np.nan, 2, np.nan],
                     'four':[3, 4, np.nan, 3],
                     'five':[5, np.nan, 1, np.nan],
                     'six': [np.nan, 5, np.nan, 5],
                     'seven':[np.nan, np.nan, np.nan, 4]},
                     index = list('ABCD'))

In [3]:
data

one  two  three  four  five  six  seven
A  4.0  NaN    5.0   3.0   5.0  NaN    NaN
B  NaN  4.0    NaN   4.0   NaN  5.0    NaN
C  2.0  NaN    2.0   NaN   1.0  NaN    NaN
D  NaN  5.0    NaN   3.0   NaN  5.0    4.0

# 找到和A趣味相投的人

## 余弦相似度

In [4]:
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
sim_AB = cosine_similarity(data.loc['A',:].fillna(0).values.reshape(1, -1),
                           data.loc['B',:].fillna(0).values.reshape(1, -1))
# 新版本 Serise 没有 reshape

In [9]:
sim_AB

array([[0.18353259]])

In [10]:
sim_AC = cosine_similarity(data.loc['A',:].fillna(0).values.reshape(1, -1),
                           data.loc['C',:].fillna(0).values.reshape(1, -1))

In [11]:
sim_AC

array([[0.88527041]])

## 去中心化

In [14]:
data_center = data.apply(lambda x: x-x.mean(), axis=1)

In [15]:
sim_AB = cosine_similarity(data_center.loc['A',:].fillna(0).values.reshape(1, -1),
                           data_center.loc['B',:].fillna(0).values.reshape(1, -1))

In [16]:
sim_AB

array([[0.30772873]])

In [17]:
sim_AC = cosine_similarity(data_center.loc['A',:].fillna(0).values.reshape(1, -1),
                           data_center.loc['C',:].fillna(0).values.reshape(1, -1))

In [18]:
sim_AC

array([[-0.24618298]])

In [19]:
sim_AD = cosine_similarity(data_center.loc['A',:].fillna(0).values.reshape(1, -1),
                           data_center.loc['D',:].fillna(0).values.reshape(1, -1))

In [20]:
sim_AD

array([[0.56818182]])

# 预测A对two的评分

In [21]:
(sim_AD*data.loc['D', 'two'] + sim_AB*data.loc['B', 'two'])/(sim_AD+sim_AB)

array([[4.64867562]])