In [2]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
data = pd.DataFrame({'U1':[2, np.nan, 1, np.nan, 3],
                     'U2':[np.nan, 3, np.nan, 4, np.nan],
                     'U3':[4, np.nan, 5, 4, np.nan],
                     'U4':[np.nan, 3, np.nan, 4, np.nan],
                     'U5':[5, np.nan, 4, np.nan, 5]})
data.index = ['S1', 'S2', 'S3', 'S4', 'S5']
# 列代表用户，行代表物品

In [7]:
data

U1   U2   U3   U4   U5
S1  2.0  NaN  4.0  NaN  5.0
S2  NaN  3.0  NaN  3.0  NaN
S3  1.0  NaN  5.0  NaN  4.0
S4  NaN  4.0  4.0  4.0  NaN
S5  3.0  NaN  NaN  NaN  5.0

# 预测U3对S5的评分

In [8]:
data_center = data.apply(lambda x: x-x.mean(), axis=1)  # 对行去中心化

In [9]:
data_center

U1   U2        U3   U4        U5
S1 -1.666667  NaN  0.333333  NaN  1.333333
S2       NaN  0.0       NaN  0.0       NaN
S3 -2.333333  NaN  1.666667  NaN  0.666667
S4       NaN  0.0  0.000000  0.0       NaN
S5 -1.000000  NaN       NaN  NaN  1.000000

In [10]:
sim = []
for i in range(len(data_center)):
    simliarity = cosine_similarity(
        np.nan_to_num(data.iloc[-1].values).reshape(1,-1),  # data.iloc[-1].values 取最后一行
        np.nan_to_num(data.iloc[i].values).reshape(1,-1)
    )
    sim.append(simliarity)

In [11]:
sim

[array([[0.79253049]]),
 array([[0.]]),
 array([[0.60864454]]),
 array([[0.]]),
 array([[1.]])]

In [12]:
rate_u3 = pd.DataFrame({
    'rating': data['U3'],
    'sim': sim
})

In [13]:
rate_u3

rating                     sim
S1     4.0  [[0.7925304884756161]]
S2     NaN                 [[0.0]]
S3     5.0  [[0.6086445426287076]]
S4     4.0                 [[0.0]]
S5     NaN  [[0.9999999999999998]]

In [14]:
rate_u3 = rate_u3.dropna()

In [16]:
rate_u3['sim'] = rate_u3['sim'].map(lambda x: x[0][0])

C:\Users\luhe\AppData\Local\Temp\ipykernel_39504\1164271930.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rate_u3['sim'] = rate_u3['sim'].map(lambda x: x[0][0])


In [21]:
sim_u3 = rate_u3.sort_values('sim', ascending=False)[:2].copy()

In [22]:
sim_u3

rating       sim
S1     4.0  0.792530
S3     5.0  0.608645

In [23]:
(sim_u3.rating*sim_u3.sim).sum()/sim_u3.sim.sum()

4.43438152202085