In [1]:
import numpy as np
import pandas as pd

# 统计方法

In [2]:
data = pd.DataFrame(np.random.randn(9,6), columns=list('abcdef'))

In [3]:
data

a         b         c         d         e         f
0 -1.275374 -1.716434  0.378963 -0.570430 -0.838515 -0.580085
1 -0.379262 -0.194995  1.712992  0.647108  0.716119  1.556584
2 -0.560927 -1.532025 -0.477870  0.543167  1.043725 -0.748711
3  1.628004 -0.179523  1.089616  1.102608  0.333088 -0.942939
4 -1.625205 -0.379636  1.757878  0.963458  0.576844  1.185927
5 -1.506126 -0.228909  0.136160 -0.638295 -0.210192  0.556669
6 -0.612531 -1.607560  0.165254 -1.736242 -1.267426  0.397543
7 -0.051339 -0.155817  1.433560 -0.135979 -0.486893  0.890941
8  0.964277  1.297130 -0.521509 -0.057722 -0.240441 -0.036027

In [4]:
data.head(3)

a         b         c         d         e         f
0 -1.275374 -1.716434  0.378963 -0.570430 -0.838515 -0.580085
1 -0.379262 -0.194995  1.712992  0.647108  0.716119  1.556584
2 -0.560927 -1.532025 -0.477870  0.543167  1.043725 -0.748711

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       9 non-null      float64
 1   b       9 non-null      float64
 2   c       9 non-null      float64
 3   d       9 non-null      float64
 4   e       9 non-null      float64
 5   f       9 non-null      float64
dtypes: float64(6)
memory usage: 560.0 bytes


In [6]:
data.iloc[2,2] = np.nan

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       9 non-null      float64
 1   b       9 non-null      float64
 2   c       8 non-null      float64
 3   d       9 non-null      float64
 4   e       9 non-null      float64
 5   f       9 non-null      float64
dtypes: float64(6)
memory usage: 560.0 bytes


In [8]:
data.describe()

a         b         c         d         e         f
count  9.000000  9.000000  8.000000  9.000000  9.000000  9.000000
mean  -0.379832 -0.521974  0.769114  0.013075 -0.041521  0.253322
std    1.098543  0.961703  0.844814  0.910042  0.764763  0.887484
min   -1.625205 -1.716434 -0.521509 -1.736242 -1.267426 -0.942939
25%   -1.275374 -1.532025  0.157980 -0.570430 -0.486893 -0.580085
50%   -0.560927 -0.228909  0.734290 -0.057722 -0.210192  0.397543
75%   -0.051339 -0.179523  1.503418  0.647108  0.576844  0.890941
max    1.628004  1.297130  1.757878  1.102608  1.043725  1.556584

In [9]:
data.sum(0)  #第一行

a   -3.418484
b   -4.697769
c    6.152914
d    0.117672
e   -0.373692
f    2.279902
dtype: float64

In [10]:
data.idxmax(0)  # 返回最大值索引

a    3
b    8
c    4
d    3
e    2
f    1
dtype: int64

In [11]:
data.a.idxmax()

3

In [12]:
data.a[data.a.idxmax()]  # 返回最大值

1.6280042571252895

In [13]:
data = pd.DataFrame(np.random.randint(1,10,size=(5,7)))  # 范围1到10

In [14]:
data

0  1  2  3  4  5  6
0  4  1  7  8  7  3  6
1  1  5  4  5  6  6  9
2  4  3  7  5  3  8  3
3  9  7  5  5  6  1  6
4  7  7  1  8  1  7  8

In [15]:
np.unique(data)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [16]:
data.iloc[:,-1]

0    6
1    9
2    3
3    6
4    8
Name: 6, dtype: int32

In [17]:
data.iloc[:,-1].unique()

array([6, 9, 3, 8])

In [18]:
data.iloc[2].unique()

array([4, 3, 7, 5, 8])

In [19]:
data.iloc[:,-2].value_counts()   # 统计每个值出现的次数

3    1
6    1
8    1
1    1
7    1
Name: 5, dtype: int64

In [20]:
s = pd.Series(['a', 'b', 'b', 'b', 'b', 'b', 'a', 'c'])

In [21]:
s.value_counts()

b    5
a    2
c    1
dtype: int64

# 应用函数

## 成员关系判断

In [22]:
s.isin(['a','c'])

0     True
1    False
2    False
3    False
4    False
5    False
6     True
7     True
dtype: bool

In [24]:
data.apply(lambda x: x.max()-x.min(), axis=0)

0    8
1    6
2    6
3    3
4    6
5    7
6    6
dtype: int32

In [28]:
data

0  1  2  3  4  5  6
0  4  1  7  8  7  3  6
1  1  5  4  5  6  6  9
2  4  3  7  5  3  8  3
3  9  7  5  5  6  1  6
4  7  7  1  8  1  7  8

In [31]:
data.columns = list("abcdefg")

In [32]:
data

a  b  c  d  e  f  g
0  4  1  7  8  7  3  6
1  1  5  4  5  6  6  9
2  4  3  7  5  3  8  3
3  9  7  5  5  6  1  6
4  7  7  1  8  1  7  8

In [33]:
data.a.apply(lambda x: x+10)

0    14
1    11
2    14
3    19
4    17
Name: a, dtype: int64

## 元素级应用函数

In [34]:
data.applymap(lambda x: x**2 + x + 3)  #和广播效果类似

a   b   c   d   e   f   g
0  23   5  59  75  59  15  45
1   5  33  23  33  45  45  93
2  23  15  59  33  15  75  15
3  93  59  33  33  45   5  45
4  59  59   5  75   5  59  75

In [36]:
data['g'] = ['ss','fge','sgs','gega','gas']

In [37]:
data

a  b  c  d  e  f     g
0  4  1  7  8  7  3    ss
1  1  5  4  5  6  6   fge
2  4  3  7  5  3  8   sgs
3  9  7  5  5  6  1  gega
4  7  7  1  8  1  7   gas

In [38]:
data['g'] = data.g.apply(lambda x: x.title())  # g列字符串首字母大写

In [39]:
data

a  b  c  d  e  f     g
0  4  1  7  8  7  3    Ss
1  1  5  4  5  6  6   Fge
2  4  3  7  5  3  8   Sgs
3  9  7  5  5  6  1  Gega
4  7  7  1  8  1  7   Gas